{% set name = "gurobi-logtools" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ba0ac6d25b3056d9961f3436f3a919a7ea183292445a4956b52a74b2f82132f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - ipywidgets
    - numpy
    - pandas
    - plotly
    - xlsxwriter

test:
  imports:
    - gurobi_logtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Gurobi/gurobi-logtools
  summary: Gurobi log file tools for parsing and exploring data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
