{% set name = "gurobi-logtools" %}
{% set version = "4.0.1" %}
{% set python_min = "3.9" %}
{% set python_max = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 06e2246f886fa7d635678b91ca3ddea54ab2b1fafc15531242d7df4dd42cd0fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }},<={{ python_max }}
    - ipywidgets
    - numpy
    - pandas
    - plotly
    - xlsxwriter
    - nbformat>=4.2.0

test:
  imports:
    - gurobi_logtools
  commands:
    - pip check
    - python -m pytest -vvv
    - ls -R
# The tests use relative imports,
# thus the prefix "python -m " is necessary to add
# a root folder to sys.path temporarily    
#  - cd tests; 
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=8.1,<9
  source_files:
    - tests/


about:
  home: https://github.com/Gurobi/gurobi-logtools
  summary: Gurobi log file tools for parsing and exploring data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
