{% set name = "gurobi_logtools" %}
{% set version = "4.0.0" %}
{% set python_min = "3.9" %}
{% set python_max = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9ad15a361e69b6ca1ced466676b1ba5b3572837c26305163df1617c765a09967

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - ipywidgets
    - numpy
    - pandas
    - plotly
    - xlsxwriter
    - nbformat >=4.2.0

test:
  imports:
    - gurobi_logtools
  commands:
    - echo "Print all paths in current dir"
    - ls -R
    - echo "Finished printing"
    - python -m pytest -vvv
  requires:
    - python {{ python_min }}
    - pytest >=8.1,<9

about:
  home: https://github.com/Gurobi/gurobi-logtools
  summary: Gurobi log file tools for parsing and exploring data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
