{% set name = "gurobi-logtools" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gurobi-logtools-{{ version }}.tar.gz
  sha256: 9f1d038ff204f6d6f61dde86c6395aab7264f686d5ebef090c8821321f6e6ff4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - ipywidgets
    - numpy
    - pandas
    - plotly
    - xlsxwriter

test:
  imports:
    - gurobi_logtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Gurobi/gurobi-logtools
  summary: Gurobi log file tools for parsing and exploring data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
