{% set name = "gurobi-logtools" %}
{% set version = "3.2.0" %}
{% set python_min = "3.8" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ba0ac6d25b3056d9961f3436f3a919a7ea183292445a4956b52a74b2f82132f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - ipywidgets
    - numpy
    - pandas
    - plotly
    - xlsxwriter

test:
  imports:
    - gurobi_logtools
  commands:
    - pip check
    - ls -R
    # The tests use relative imports,
    # thus the prefix "python -m " is necessary to add
    # a root folder to sys.path temporarily
    - cd tests
    - ls -R
    - python -m pytest -vvv
    #- python -m gurobi_logtools test.xlsx data/*.log 
    #- python -m gurobi_logtools --timelines test.xlsx data/*.log 
    #- python -m gurobi_logtools -t test.xlsx data/*.log 
    #- python -m gurobi_logtools --write-to-dir nicenames summary.xlsx tests/assets/combined/*.log
  requires:
    - python {{ python_min }}
    - pip
    - pytest 
  source_files:
    - .

about:
  home: https://github.com/Gurobi/gurobi-logtools
  summary: Gurobi log file tools for parsing and exploring data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
